### ISSUE TITLE
Possible to have another branch that works with jQuery 1.7?

### ISSUE THREAD

**Issue by skube** [adobe-accessibility/Accessible-Mega-Menu#11]
I'm not sure how easy this would be to do, but is it possible to have a version of this that works with jQuery 1.7?  I trying to implement on a large website I can't simply upgrade the jQuery version across the board without some other functionality potentially breaking.

**Comment by llahnoraa** [comment]
+1

Percussion.com (CMS) relied on 1.7.2 which could be a problematic. Is there a way to make 1.7.x works somehow? Thank you.

**Comment by mattmay** [comment]
This project is not under active maintenance.
