### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by frob** [adobe-accessibility/Accessible-Mega-Menu#24]

**Comment by awkawk** [comment]
Not actively.  This was posted as an example that we wanted to provide source code to help interested devs.  Some fixes have been made but it is mostly an example from a past iteration of Adobe's menu system.

**Comment by llahnoraa** [comment]
So it's safe to implement this on college website, right?

**Comment by frob** [comment]
I can name three or four higher ed sites that are using this. There are no major bugs that I can think of. 

Be warned that it isn't very flexible. What it does is what it does and it is difficult to get it to do otherwise.
