### ISSUE TITLE
Top-level links not firing megamenu in Safari

### ISSUE THREAD

**Issue by unidb** [adobe-accessibility/Accessible-Mega-Menu#54]
Hello,

I hope someone might be able to help with this issue. We've used the Adobe Accessible Mega Menu code here https://www.liverpool.ac.uk/new-header/ and it works very well and fires the megamenu exactly as required on all browsers except Safari on Mac desktop. It's fine in iOS. 

On clicking the Study with Liverpool/Our research/About us links, the JS should append a class of "open" which calls the CSS to display the megamenu content.  This does not happen in Safari on Mac Desktop. Nothing at all seems to happen on click. Can anyone help us to debug it and find out why this is happening?

Many thanks

**Comment by majornista** [comment]
Hi,

In Safari, turning on Preferences > Advanced > Accessibility: Press Tab to highlight each item on a webpage seems to solve the issue, but it will remain a problem for mouse users using the default browser settings. I'll see if I can provide a fix.

**Comment by unidb** [comment]
Hello,

Thanks so much for looking at this issue.

I’ve just tried as you suggested below, using www.browserstack.com<http://www.browserstack.com>, and I can see that working now using an instance of Sierra on Mac. Although, as you say, it would have remained a problem for mouse users.

A fix using default settings+mouse would be extremely welcome!

Many thanks

**Comment by majornista** [comment]
Did you remove mouseover opening on hover here: https://github.com/adobe-accessibility/Accessible-Mega-Menu/blob/master/js/jquery-accessibleMegaMenu.js#L656?

This is a much requested feature, but it seems to be messing with the current behavior.

**Comment by majornista** [comment]
Just committed a few, long overdue, fixes that may help.

**Comment by majornista** [comment]
You should be able to swap out jquery-accessibleMegaMenu.js and, unless there were other significant modifications to the script for your site, it should now, by default, expand or collapse the dropdown menus on clicking a top nav item rather than by hovering over it.

**Comment by unidb** [comment]
After some initial testing, this appears to work really well. Do you maintain this code as a side project? My team were very impressed that this was sorted so quickly! Thanks so much for your help!

**Comment by majornista** [comment]
Glad to see it's working for you. To be honest, I had done some work on this back in March to implement the much requested change to have the menus open with a click, rather than have different behaviors on Desktop and Mobile, but hadn't committed the changes. I haven't really been maintaining this project, because I've needed to focus on other work. I hope it provides a good example for developers needing to implement an accessible mega menu on their own, but it is not an ongoing project.
