### ISSUE TITLE
Two mouse clicks required for top level menu in Firefox, IE, Opera

### ISSUE THREAD

**Issue by tlexa** [adobe-accessibility/Accessible-Mega-Menu#8]
When first loading a page using this menu in Firefox 27, IE 10, or Opera 12.16, it seems to require one mouse click on any top level menu (ie, from the index.html sample: Perceivable | Operable | Understandable | Robust) to focus, then a second click on any other top level menu to load the URL. 
Using Chrome 32.0.1700.107 and Safari 5.1.7 it works with only a single click.

**Comment by Spone** [comment]
I still have this issue in the current version of Firefox.
